package face_recognition.dto.notification;

import face_recognition.model.Notification;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;

@Data
@Builder
public class NotificationAdminResponse {
    private Long id;
    private String title;
    private String content;
    private String type;
    private String target;
    private String classRoomName;
    private LocalDateTime createdAt;
    private LocalDateTime expiredAt;
    private Boolean isActive;
    private Boolean isAutoGenerated;
    private int recipientCount;

    public static NotificationAdminResponse from(Notification n) {
        boolean active = Boolean.TRUE.equals(n.getIsActive())
                && (n.getExpiredAt() == null || n.getExpiredAt().isAfter(LocalDateTime.now()));
        return NotificationAdminResponse.builder()
                .id(n.getId())
                .title(n.getTitle())
                .content(n.getContent())
                .type(n.getType().name())
                .target(n.getTarget().name())
                .classRoomName(n.getClassRoom() != null ? n.getClassRoom().getName() : null)
                .createdAt(n.getCreatedAt())
                .expiredAt(n.getExpiredAt())
                .isActive(active)
                .isAutoGenerated(n.getIsAutoGenerated())
                .recipientCount(n.getRecipients() != null ? n.getRecipients().size() : 0)
                .build();
    }
}